"""FinDocIQ — live demo Space.

Runs the text-retrieval lane of the full pipeline on a free CPU Space:
BGE-small dense retrieval over page text, with answers generated by Gemini
reading the retrieved page *images* (so charts and tables are read
directly). The full system — ColQwen2.5 late-interaction visual retrieval
fused with this text lane via RRF over Qdrant — is in the GitHub repo and
needs more compute than a free Space provides.
"""

import json
import os
import time
from pathlib import Path

import numpy as np
import streamlit as st

DATA_DIR = Path(__file__).parent / "data"
TOP_K = 5
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-2.5-flash")
REPO_URL = "https://github.com/usamahassan965/findociq"

SYSTEM_PROMPT = (
    "You are a financial document analyst. Answer the user's question using ONLY the "
    "provided document page images. Read charts, tables, and figures directly from the "
    "images. Cite every claim with the source in the form [doc_name p.N]. If the pages "
    "do not contain the answer, say so explicitly instead of guessing."
)

SAMPLE_QUESTIONS = [
    "What is the forecast for WTI crude oil prices?",
    "How did Berkshire's insurance business perform in 2024?",
    "What does the EIA expect for US natural gas production?",
]


@st.cache_resource
def load_resources():
    from google import genai
    from sentence_transformers import SentenceTransformer

    records = json.loads((DATA_DIR / "index.json").read_text(encoding="utf-8"))
    matrix = np.array([r["embedding"] for r in records], dtype=np.float32)
    embedder = SentenceTransformer("BAAI/bge-small-en-v1.5")
    client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])
    return records, matrix, embedder, client


def retrieve(query: str, records, matrix, embedder) -> list[dict]:
    q = np.asarray(
        embedder.encode(
            f"Represent this sentence for searching relevant passages: {query}",
            normalize_embeddings=True,
        ),
        dtype=np.float32,
    )
    scores = matrix @ q
    order = np.argsort(-scores)[:TOP_K]
    return [{**records[i], "score": float(scores[i])} for i in order]


def stream_answer(client, question: str, hits: list[dict]):
    """Yield answer text chunks from Gemini as they arrive."""
    from google.genai import types

    parts = [
        types.Part.from_bytes(
            data=(DATA_DIR / "pages" / h["image"]).read_bytes(), mime_type="image/png"
        )
        for h in hits
    ]
    page_list = "\n".join(
        f"- Image {i + 1}: {h['doc_name']} p.{h['page_number']}" for i, h in enumerate(hits)
    )
    parts.append(
        types.Part.from_text(text=f"Document pages provided:\n{page_list}\n\nQuestion: {question}")
    )
    for chunk in client.models.generate_content_stream(
        model=GEMINI_MODEL,
        contents=parts,
        config=types.GenerateContentConfig(system_instruction=SYSTEM_PROMPT),
    ):
        if chunk.text:
            yield chunk.text


st.set_page_config(page_title="FinDocIQ demo", page_icon="📊", layout="wide")

st.title("📊 FinDocIQ — demo")
st.caption(
    "Multimodal financial document intelligence. Ask about the loaded documents; "
    "answers are generated by a VLM reading the retrieved page images, with citations."
)
st.info(
    "**Demo scope:** this free CPU Space runs the text-retrieval lane (BGE-small) of the "
    "pipeline. The full system adds ColQwen2.5 visual retrieval fused via RRF over Qdrant — "
    f"see the [GitHub repo]({REPO_URL}). Loaded documents: **Berkshire Hathaway 2024 "
    "shareholder letter** and **EIA Short-Term Energy Outlook**.",
    icon="ℹ️",
)

if "history" not in st.session_state:
    st.session_state.history = []

for turn in st.session_state.history:
    with st.chat_message(turn["role"]):
        st.markdown(turn["content"])

question = st.chat_input("Ask about the documents...")
if not question and not st.session_state.history:
    cols = st.columns(len(SAMPLE_QUESTIONS))
    for col, sample in zip(cols, SAMPLE_QUESTIONS):
        if col.button(sample):
            question = sample

if question:
    st.session_state.history.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.markdown(question)

    records, matrix, embedder, client = load_resources()

    with st.chat_message("assistant"):
        with st.spinner("Retrieving pages..."):
            t0 = time.perf_counter()
            hits = retrieve(question, records, matrix, embedder)
            retrieval_s = time.perf_counter() - t0

        timing = {"first_token_s": None}
        t_gen = time.perf_counter()

        def _stream():
            for chunk in stream_answer(client, question, hits):
                if timing["first_token_s"] is None:
                    timing["first_token_s"] = time.perf_counter() - t_gen
                yield chunk

        answer = st.write_stream(_stream)
        generation_s = time.perf_counter() - t_gen

        st.caption(
            f"⏱ retrieval {retrieval_s * 1000:.0f} ms · "
            f"first token {timing['first_token_s']:.1f} s · "
            f"full answer {generation_s:.1f} s"
            if timing["first_token_s"] is not None
            else f"⏱ retrieval {retrieval_s * 1000:.0f} ms"
        )

        with st.expander(f"📄 Retrieved pages ({len(hits)})", expanded=False):
            cols = st.columns(min(len(hits), 3) or 1)
            for i, hit in enumerate(hits):
                with cols[i % len(cols)]:
                    st.image(str(DATA_DIR / "pages" / hit["image"]))
                    st.caption(
                        f"**{hit['doc_name']}** p.{hit['page_number']} · "
                        f"cosine {hit['score']:.4f}"
                    )

    st.session_state.history.append({"role": "assistant", "content": answer})
